### ISSUE TITLE
[Dev] Moonshot runner for doc

### ISSUE THREAD

**Issue by jbcaillau** [control-toolbox/Tutorials.jl#13]
@amontoison can you please add runner moonshot for the action below (that builds the doc)? then i will update the code so that it runs on GPU when CUDA is available 🤞🏽(CPU otherwise)
https://github.com/control-toolbox/Tutorials.jl/blob/main/.github/workflows/Documentation.yml

NB. still, can you please check that the action defaults to GitHub runners if moonshot is down?

**Comment by amontoison** [comment]
Yes, I can do that :)
PS: You can't target another GitHub runners if moonshot is down.

**Comment by amontoison** [comment]
@jbcaillau I quickly setup `moonshot` on this repo.
You can use for the documentation with something like this:
```yaml
jobs:
  documentation-moonshot:
    env:
      CUDA_VISIBLE_DEVICES: 1
      JULIA_DEPOT_PATH: /scratch/github-actions/julia_depot_tutorials
      DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: self-hosted
    strategy:
      matrix:
        os: [ubuntu-22.04]
        julia-version: ['1']
        julia-arch: [x64]

    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.julia-version }}
          arch: ${{ matrix.julia-arch }}
      - run: julia --project=docs/ docs/make.jl
```
